GET http://localhost:5000/

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "uid": 1,
    "password": "123456"
}

###

POST http://localhost:5000/newbooking
Content-Type: application/json

{
    "uid": 1,
    "travelPurpose": "bizness",
    "expectedDistance": 3,
    "pickupDateTime": "08:00 PM,  21-11-2022",
    "pickupVenue": "office",
    "arrivalDateTime": "01:00 PM,  21-11-2022",
    "additionalInfo": null,
    "reqDateTime": "2022-07-31 15:42:10.662450"
}

###

GET http://localhost:5000/history/1

###

POST http://localhost:5000/admincheck
Content-Type: application/json

{"uname":"abcd","password":"efgh"}

###

GET http://localhost:5000/adminlogin