GET http://localhost:5000/

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "uid": 1,
    "password": "123456"
}

###

POST http://localhost:5000/newbooking
Content-Type: application/json

{
    "uid": 1,
    "travelPurpose": "bizness",
    "expectedDistance": 3,
    "pickupDateTime": "08:00 PM,  21-11-2022",
    "pickupVenue": "office",
    "arrivalDateTime": "01:00 PM,  21-11-2022",
    "additionalInfo": null,
    "reqDateTime": "2022-07-31 15:42:10.662450"
}

###

GET http://localhost:5000/history/1

###

POST http://localhost:5000/admincheck
Content-Type: application/json

{"uname":"abcd","password":"efgh"}

###

GET http://localhost:5000/adminlogin


###

GET http://localhost:5000/adminpage
Content-Type: application/json

{"token":"randomstuff"}

###

POST http://localhost:5000/getbookingrequests
Content-Type: application/json

{"num":1}


###

POST http://localhost:5000/newvehicleinfo
Content-Type: application/json

{
        "bookingID": 1,
        "vehRegNum": "abc",
        "vehModel": "some car",
        "licenseExpDate": "2022-09-12",
        "insuranceExpDate": "2022-09-12",
        "pucExpDate": "2022-09-12",
        "driverName": "rohan",
        "driverAddress": "malabaar",
        "licenseNum": "some string",
        "driverContact": 8342023433,
        "travAgentContact": null
}


###


POST http://127.0.0.1:5000/getvehicleinfo
Content-Type: application/json

{"bookingID":1}

###

GET http://localhost:5000/getmanagerrequests?mng_id=5